apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30009
  selector:
    app: webapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: messageboard_api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DOTNET_ENVIRONMENT
          value: K8S
        volumeMounts:
        - name: config
          mountPath: /app/appsettings.K8S.json
          subPath: appsettings.K8S.json
      volumes:
      - name: config
        configMap:
          name: apiconfig
